"""added tmp tables and fixed relationships

Revision ID: 2c95d004ef94
Revises: 5f547a4f75d2
Create Date: 2025-04-29 22:56:17.123768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c95d004ef94'
down_revision: Union[str, None] = '5f547a4f75d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutes_old',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('institute', sa.String(), nullable=False),
    sa.Column('institute_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutes_tmp',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('institute', sa.String(), nullable=False),
    sa.Column('institute_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups_old',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_', sa.String(), autoincrement=False, nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes_old.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups_tmp',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_', sa.String(), autoincrement=False, nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes_tmp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_old',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('student', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('leader', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups_old.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_tmp',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('student', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('leader', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups_tmp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('old_students')
    op.drop_table('old_groups_')
    op.drop_table('old_institutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('old_groups_',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('institute_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['old_institutes.id'], name='old_groups__institute_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='old_groups__pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('old_institutes',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('institute', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('institute_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='old_institutes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('old_students',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leader', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['old_groups_.id'], name='old_students_group_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='old_students_pkey')
    )
    op.drop_table('students_tmp')
    op.drop_table('students_old')
    op.drop_table('groups_tmp')
    op.drop_table('groups_old')
    op.drop_table('institutes_tmp')
    op.drop_table('institutes_old')
    # ### end Alembic commands ###
