"""add old tables

Revision ID: 47e75e17e8a2
Revises: 88b395c5292c
Create Date: 2025-04-21 00:16:23.801523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e75e17e8a2'
down_revision: Union[str, None] = '88b395c5292c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('old_institutes',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('institute', sa.String(), nullable=False),
    sa.Column('institute_num', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('old_groups_',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_', sa.String(), autoincrement=False, nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['old_institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('old_students',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('student', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('leader', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['old_groups_.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('old_students')
    op.drop_table('old_groups_')
    op.drop_table('old_institutes')
    # ### end Alembic commands ###
