"""renamed datetime column

Revision ID: 5f547a4f75d2
Revises: 47e75e17e8a2
Create Date: 2025-04-29 21:30:55.008482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f547a4f75d2'
down_revision: Union[str, None] = '47e75e17e8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups_', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('groups_', 'date')
    op.add_column('institutes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('institutes', 'date')
    op.add_column('old_groups_', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('old_groups_', 'date')
    op.add_column('old_institutes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('old_institutes', 'date')
    op.add_column('old_students', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('old_students', 'date')
    op.add_column('reports_archive', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('reports_archive', 'date')
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('students', 'date')
    op.add_column('students_archive', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('students_archive', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_archive', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('students_archive', 'created_at')
    op.add_column('students', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('students', 'created_at')
    op.add_column('reports_archive', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('reports_archive', 'created_at')
    op.add_column('old_students', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('old_students', 'created_at')
    op.add_column('old_institutes', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('old_institutes', 'created_at')
    op.add_column('old_groups_', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('old_groups_', 'created_at')
    op.add_column('institutes', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('institutes', 'created_at')
    op.add_column('groups_', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('groups_', 'created_at')
    # ### end Alembic commands ###
