"""initial

Revision ID: 88b395c5292c
Revises: 
Create Date: 2025-04-21 00:05:05.853689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b395c5292c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutes',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('institute', sa.String(), nullable=False),
    sa.Column('institute_num', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_content', sa.String(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute', sa.String(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('group_', sa.Integer(), nullable=False),
    sa.Column('student', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups_',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_', sa.String(), autoincrement=False, nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('student', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('leader', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups_.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('groups_')
    op.drop_table('students_archive')
    op.drop_table('reports_archive')
    op.drop_table('institutes')
    # ### end Alembic commands ###
